apiVersion: apps/v1
kind: Deployment
metadata:
 name: producerapi
spec:
 replicas: 3
 selector:
   matchLabels:
     app: producerapi
 template:
   metadata:
     labels:
       app: producerapi
   spec:
     containers:
     - name: producerapi
       image: den86/producerapi